Chapter.create(chap: "Introduction",course_id: 1 )
Chapter.create(chap: "Basic",course_id: 1)
Chapter.create(chap: "Varilables",course_id: 1)
Chapter.create(chap: "Classes",course_id: 1)
Chapter.create(chap: "Data Structures",course_id: 1)
Chapter.create(chap: "OOPS",course_id: 1)
Chapter.create(chap: "Machine Learning",course_id: 1)
Chapter.create(chap: "Artificial Inteligence",course_id: 1)
Chapter.create(chap: "IO",course_id: 1)
Chapter.create(chap: "Summary",course_id: 1)